[package]
name = "rust_rocket_starter"
version = "0.0.1"
authors = ["hieumdoan@gmail.com"]

[dependencies]
diesel = "2.0.2"
diesel_cli = { version = "1.4.1", default-features = false, features = ["postgres"] }
rocket = "0.4.11"
rocket_contrib = "0.4.11"
serde = { version = "1.0.151", features = ["derive"] }
